PPF hypercube
nanograv/enterprise pull request #389
Opened 2024-07-12 15:38 UTC by astrolamb

I forgot to make a PR of my fixes to PR #366. 

I'm adding a method to the `PTA` object to compute the PPF of a parameter sampled from a unit hypercube. This allows the user to easily use enterprise `PTA` objects in nested samplers.

There is also a unit test for the method.

2024-11-27 19:10 UTC, vhaasteren approved these changes
This all looks fine to me

2024-12-09 06:52 UTC, vhaasteren commented
Hi @astrolamb , there are two files that have changes related to twine secrets and bumping the version. That should not be included in a PR like this one. Can you remove those?

2024-12-09 06:53 UTC, vhaasteren requested changes
Strip out unrelated changes

2024-12-09 06:53 UTC, vhaasteren commented on .github/workflows/ci_test.yml
> +        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
This one should not be in this PR

2024-12-09 06:53 UTC, vhaasteren commented on setup.cfg
> +current_version = 3.4.1
This should not be in this PR

2025-01-03 22:44 UTC, astrolamb commented
Apologies @vhaasteren, I'm not sure why those edit were in there. I've reverted those changes

2025-01-09 15:49 UTC, vhaasteren commented
Great. Now you just need to do some linting:

```
would reformat tests/test_vector_parameter.py
would reformat enterprise/signals/signal_base.py
```

Perhaps best is not to let black re-format the whole file, but only the lines that you changed in this PR. You can give black a line range, or you can just manually merge in the reformatting of black. There are more complicated things to do, but above is what I typically do

2025-01-10 19:50 UTC, astrolamb commented
@vhaasteren linting done!

2025-01-10 20:10 UTC, merged